Bug/cors
Tournamanager/api pull request #104
Opened 2019-11-04 15:19 UTC by lmtjanssen

fixes #103

2019-11-05 08:42 UTC, lfb0801 requested changes
remove everything that has nothing to do with the claimed issue.

2019-11-11 08:52 UTC, MindHawk requested changes

2019-11-11 08:52 UTC, MindHawk commented on src/main/java/com/fontys/api/mutations/UserMutation.java
> +    public User createUser(String uuid) { return userService.createUser(uuid); }
Not part of issue

2019-11-11 08:52 UTC, MindHawk commented on src/main/java/com/fontys/api/repositories/UserRepository.java
> +    Optional<User> findByUuid(String UUID);
Not part of issue

2019-11-11 08:52 UTC, MindHawk commented on src/main/java/com/fontys/api/service/UserService.java
> +    public User createUser(String uuid) { return userRepository.save(new User(uuid)); }
Not part of issue

2019-11-11 08:52 UTC, MindHawk commented on src/main/java/com/fontys/api/service/UserService.java
> +        return userRepository.findByUuid(uuid);
Not part of issue

2019-11-11 08:52 UTC, MindHawk commented on src/main/resources/graphql/schema.graphqls
> +    deleteUser(uuid:String!):String
Not part of issue

2019-11-11 08:52 UTC, MindHawk commented on src/test/java/com/fontys/api/service/UserServiceTest.java
> +    void deleteTeamShouldReturnDeletedString() {
Not part of issue

2019-11-11 09:00 UTC, MindHawk approved these changes
Everything changed is now relevant to the issue.

2019-11-11 09:06 UTC, larsvandriel approved these changes

2019-11-11 09:09 UTC, MindHawk commented
Different pull request fixes same issue.

2019-11-11 09:09 UTC, closed without merging