Add Team To Tournament
Tournamanager/api pull request #116
Opened 2019-11-14 00:24 UTC by larsvandriel

Closes #115

2019-11-18 10:52 UTC, chf3kl9 requested changes

2019-11-18 10:52 UTC, chf3kl9 commented on src/main/java/com/fontys/api/service/TournamentService.java
> +        Tournament tournamentOld = validateTournament(id);
We don't need to rename this to tournamentOld, as we don't use any 'tournamentNew' or 'tournament'

2019-11-18 10:52 UTC, chf3kl9 commented on src/test/java/com/fontys/api/service/TournamentServiceTest.java
> +        Tournament t = new Tournament(1, "testTournament", null, new User("uuid"), 2, new ArrayList<>());
We still have the constructor that does not require Teams, so this isn't necessary to do

2019-11-18 10:52 UTC, chf3kl9 commented on src/test/java/com/fontys/api/service/TournamentServiceTest.java
> +        Tournament tournament = new Tournament(1, "testTournament", "description", user, 2, new ArrayList<>());
Ditto

2019-11-18 10:52 UTC, chf3kl9 commented on src/test/java/com/fontys/api/service/TournamentServiceTest.java
> +        Tournament result = new Tournament(1, "testTournamentNew", "descriptionNew", user1, 4, new ArrayList<>());
Ditto

2019-11-18 10:52 UTC, chf3kl9 commented on src/main/java/com/fontys/api/service/TournamentService.java
> +                return "The tournament is currently filled with teams!";
Maybe we can return an error message that is more clear.
Maybe: "The tournament no longer has empty slots for this team"

2019-11-18 10:52 UTC, chf3kl9 commented on src/test/java/com/fontys/api/service/TournamentServiceTest.java
> +        assertEquals("The tournament is currently filled with teams!", response);
Same as TournamentService

> Maybe we can return an error message that is more clear.
Maybe: "The tournament no longer has empty slots for this team"

2019-11-25 08:10 UTC, chf3kl9 approved these changes

2019-11-25 08:24 UTC, lfb0801 approved these changes

2019-11-25 08:24 UTC, merged