Improvement/fix data saving
Tournamanager/api pull request #142
Opened 2020-01-13 11:59 UTC by chf3kl9

fixes issues with data saving
previously, if a team joined a tournament, the tournament would know, but the team wouldn't

2020-01-13 12:06 UTC, larsvandriel submitted a review, later dismissed

2020-01-14 14:27 UTC, lfb0801 requested changes

2020-01-14 14:27 UTC, lfb0801 commented on src/main/java/com/fontys/api/service/MatchService.java
> +        Match match1 = matchRepository.save(match);
naming of variables is weird

2020-01-14 14:27 UTC, lfb0801 commented on src/main/java/com/fontys/api/service/TeamService.java
> +            user1.getTeams().remove(team1);
brown ditto 💩

2020-01-14 14:27 UTC, lfb0801 commented on src/main/java/com/fontys/api/service/TeamService.java
> +            userRepository.save(user1);
brown ditto 💩

2020-01-14 14:27 UTC, lfb0801 commented on src/main/java/com/fontys/api/service/TeamService.java
>              teamRepository.save(team1);
brown ditto 💩

2020-01-14 14:27 UTC, lfb0801 commented on src/main/java/com/fontys/api/service/TournamentService.java
> +        team1.getTournaments().add(tournament1);
brown ditto 💩

2020-01-14 14:27 UTC, lfb0801 commented on src/main/java/com/fontys/api/service/TournamentService.java
> +        teamRepository.save(team1);
brown ditto 💩

2020-01-14 14:27 UTC, lfb0801 commented on src/main/resources/application.properties
> +server.port=8090
This choice will brake the frontend, so NAH NOT GOING TO HAPPEN CHIEF

2020-01-15 09:41 UTC, lfb0801 approved these changes
thanks for fixing the changes

2020-01-15 09:44 UTC, Zeehond99 approved these changes
Looks fine

2020-01-15 09:44 UTC, merged